name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - release/**

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.21.0
          cache: "yarn"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Build Python RPC with cx_Freeze
        run: python python_rpc/setup.py build

      - name: Build Windows Portable
        run: yarn build:win
        env:
          MAIN_VITE_API_URL: ${{ vars.MAIN_VITE_API_URL }}
          MAIN_VITE_AUTH_URL: ${{ vars.MAIN_VITE_AUTH_URL }}
          MAIN_VITE_CHECKOUT_URL: ${{ vars.MAIN_VITE_CHECKOUT_URL }}
          MAIN_VITE_WS_URL: ${{ vars.MAIN_VITE_WS_URL }}
          MAIN_VITE_NIMBUS_API_URL: ${{ vars.MAIN_VITE_NIMBUS_API_URL }}
          RENDERER_VITE_EXTERNAL_RESOURCES_URL: ${{ vars.EXTERNAL_RESOURCES_URL }}
          MAIN_VITE_EXTERNAL_RESOURCES_URL: ${{ vars.EXTERNAL_RESOURCES_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          RENDERER_VITE_SENTRY_DSN: ${{ vars.SENTRY_DSN }}
          RENDERER_VITE_REAL_DEBRID_REFERRAL_ID: ${{ vars.RENDERER_VITE_REAL_DEBRID_REFERRAL_ID }}
          RENDERER_VITE_TORBOX_REFERRAL_CODE: ${{ vars.RENDERER_VITE_TORBOX_REFERRAL_CODE }}
          MAIN_VITE_LAUNCHER_SUBDOMAIN: ${{ vars.MAIN_VITE_LAUNCHER_SUBDOMAIN }}

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-Portable-Windows
          path: |
            dist/*-portable.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            dist/*-portable.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
